### ISSUE TITLE
Java Driver - Gradle/Java error when installing from source

### ISSUE THREAD

**Issue by iabmatos** [apache/age#1217]
Hello all, 

New to AGE, I've installed the latest AGE version and is working fine on PG15. But, when I try to install the java driver, I get an error. The POM file is there. Any tips are welcome. Many thanks. Cheers, Ismael

https://repo.maven.apache.org/maven2/org/antlr/antlr4/4.12.0/antlr4-4.12.0.pom can be retrieved but...

im@imclt22:~/age-PG15/drivers/jdbc$ sudo gradle assemble
> Task :lib:generateGrammarSource FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:generateGrammarSource'.
> Could not resolve all files for configuration ':lib:antlr'.
   > Could not resolve org.antlr:antlr4:4.12.0.
     Required by:
         project :lib
      > Could not resolve org.antlr:antlr4:4.12.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/antlr/antlr4/4.12.0/antlr4-4.12.0.pom'.
            > java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by KamleshKumar427** [comment]
The issue you're encountering with the POM file might be due to network problems, incorrect dependencies, or XML formatting issues. But you can ensure these things, which may make it work:
So first ensure your internet connection is stable, **verify dependencies** and their versions, check for proper XML formatting, validate the existence and compatibility of the parent POM (antlr4-master), use a compatible **Maven version** (at least 3.8), and consider deleting the local Maven repository directory if issues persist. Additionally, the command 

> sudo gradle assemble

 appears to be unrelated to Maven; ensure you are using the correct build tool.

**Comment by iabmatos** [comment]
Hello Kamlesh, thanks for the response. It seems that the problem is with the installation of gradle. I've removed the old version of gradle and reinstalled the newest version. Then, I've tried and failed with another problem. I'll try to figure out how to resolve this.

Cheers

**Comment by jimenasansav** [comment]
Hi @iabmatos, thank you for sharing your issues! 
Please do not hesitate to share other problems you are facing. Our team is always willing to help!

**Comment by pawankukreja01** [comment]
Ensure that there are no lingering Java installations in progress. Sometimes, incomplete installations can cause conflicts. You might need to manually delete any lock files related to Java. If you’re using OpenJDK, look for the `JAVA_INSTALL_FLAG `file in relevant directories like `C:\Program Files\Java`, `C:\ProgramData\Oracle\Java`, `%UserProfile%\AppData\LocalLow\Sun\Java`, and `%UserProfile%\AppData\LocalLow\Oracle\Java`
