### ISSUE TITLE
Docker image for ARM architecture

### ISSUE THREAD

**Issue by filiprejmus** [apache/age#1541]
Hi,

are there plans to also release a docker image that supports arm?

**Comment by kevintruong** [comment]
let me handle the issue

**Comment by jrgemignani** [comment]
@filiprejmus This is something that we are looking into. But, @kevintruong your input is welcome. One of the issues with moving from Travis CI (what we previously used) to Github was losing the ability to easily build for other architectures. This move to Github was due to Apache no longer supporting Travis and Github being easier for us to migrate to.

**Comment by MuhammadTahaNaveed** [comment]
@kevintruong @filiprejmus docker image for arm is now available on dockerhub https://hub.docker.com/r/apache/age for all PG versions. If this resolves your issue, please consider closing this ticket. Thank you.

**Comment by filiprejmus** [comment]
cool thx
