### ISSUE TITLE
Drop extension doesn't drop the ag_catalog schema

### ISSUE THREAD

**Issue by jriouovh** [apache/age#1626]
**Describe the bug**

When the extension is uninstalled, the `ag_catalog` schema remains.

**How are you accessing AGE (Command line, driver, etc.)?**

Command line.

**What data setup do we need to do?**

```pgsql
create extension age;
```

**What is the necessary configuration info needed?**

Default installation using Debian packages from PGDG repositories.

**What is the command that caused the error?**

```
test=# drop extension age;
DROP EXTENSION
test=# \dn ag_catalog
    List of schemas
    Name    |  Owner   
------------+----------
 ag_catalog | postgres
(1 row)
```

**Expected behavior**

The `ag_catalog` schema should be removed by the drop extension command directly instead of manually run drop schema:

```
test=# drop schema ag_catalog;
DROP SCHEMA
test=# \dn ag_catalog
List of schemas
 Name | Owner 
------+-------
(0 rows)
```

**Environment (please complete the following information):**
- Version: 1.5.0
- PostgreSQL version: 14.11
- Debian 11

**Comment by mingfang** [comment]
I confirm that dropping the extension does not drop the ag_catalog schema.
Whatever that is causing this problem is actually causing a much bigger problem for my entire Postgres instance.
After the AGE was used once, it seems to leave a permanent dependency somewhere that's causing me to unable to delete any schemas.

The steps to recreate the problem in psql
```sql
create extension age;
drop extension age;
create database test;
\c test
drop schema public;
```
The `drop schema public` statement will fail with
```
ERROR:  schema "ag_catalog" does not exist
```

**Comment by M-Bostone** [comment]
basically your error comes up when PostgreSQL is trying to access a schema that does not exist in your current database.
try double-checking the schema name in your query, or your schema is missing, and ensure that you've got the necessary permissions required to access the schema.

**Comment by diangamichael** [comment]
Manually drop the "ag_catalog" schema using the drop schema ag_catalog; command after uninstalling the extension.
This bug disrupts the expected behavior of the extension uninstallation process and requires extra steps for cleanup. It would be ideal to have the extension removal process also remove any associated schemas automatically to streamline the uninstallation process.

**Comment by jrgemignani** [comment]
@jriouovh I will try to look into why this is happening.

**Comment by mingfang** [comment]
I believe it is normal for Postgres to NOT drop any schemas when dropping extensions; Schemas are not part of an extension's dependency.

**Comment by jrgemignani** [comment]
@jriouovh After looking into this, it does appear that schema for an extension is not dropped due to PostgreSQL. Please see the link above provided by @mingfang. As this appears to be out of the scope of an extension itself, you will need to drop the schema yourself, if desired. Hopefully, this is helpful.

**Comment by jriouovh** [comment]
Hello folks,

Indeed, as the schema is defined in the control file, PostgreSQL will not remove the schema with the extension because it may hold data and not only schema objects. So, this is not a bug.

We need to drop the schema manually when dropping the extension.

Thank you all! I'm closing this issue.

**Comment by M-Bostone** [comment]
Awesome, thanks for the update!
