### ISSUE TITLE
Edge Naming Convention/Rules

### ISSUE THREAD

**Issue by susano0** [apache/age#335]
I found that there is no naming convention for creating edge labels. It's a similar issue as mentioned in #317.

I suggest the following rules:

1. Label name must begin either with an alphabet or an underscore.
2. The name can also include numbers after the first character.
3. No spaces or other special characters except underscore should be allowed.

**Comment by jrgemignani** [comment]
Thank you for opening this issue!

As with all naming conventions, lets be sure to align ours with other graph databases for consistency.

**Comment by jrgemignani** [comment]
I think that for all names for labels, vertices, and edges, that we need to comply with Neo4j's standards. 

Additionally, I think that it is a good idea to be a bit strict with valid names due to potential security issues by allowing escaped or control characters.

So, lets follow Neo4j but disallow escaped characters.
