### ISSUE TITLE
Clarification for typo in the documentation

### ISSUE THREAD

**Issue by GhostVaibhav** [apache/age#428]
The documentation has a place where `label` is spelled as `lable` in one of the quickstart examples. Is it intentional or a typo? If so, can I make a PR to rectify it?

**Comment by KamleshKumar427** [comment]
Can you please share the link to that place?

**Comment by GhostVaibhav** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/48472541/209479080-65f8224b-863b-468d-a21d-cd1d113fb34f.png)

**Comment by imranzaheer612** [comment]
Ya, the misspelling of `label` is a common typo. ***“Lable” is sometimes used instead of label, but this is incorrect. “Lable” is not a real word and should be avoided.***

I don't think it's intentional because it will not gonna affect the result if you labeled your node something else. You can label the node whatever you like. i.e `CREATE (n:myLabel)`

**Comment by imranzaheer612** [comment]
This is an error. Because in the doc. 

* First the node is created using `n:label`
* But then we are matching nodes using `n:lable`  

This will give diff results and I guess it needs to be corrected.

![WhatsApp Image 2022-12-26 at 3 15 04 PM](https://user-images.githubusercontent.com/62287456/209537393-468063d9-3ea7-4d9f-97fa-f42ace84a391.jpeg)

* This could also be right in a way,  as these code blocks are independent from each other. In this code block we also used  `a.property = 'Node A'` but we didn't define a such node in the former code, the user has to do this by himself. So we should take this  code blocks as general block for making an edge

**Comment by KamleshKumar427** [comment]
> Ya, this could be corrected. Because in the doc.
> 
> * First the node is created using `n:label`
> * But then we are matching nodes using `n:lable`
> 
> This will give diff results and I guess it needs to be corrected.
> 
> ![WhatsApp Image 2022-12-26 at 3 15 04 PM](https://user-images.githubusercontent.com/62287456/209537393-468063d9-3ea7-4d9f-97fa-f42ace84a391.jpeg)
> 
> * This could also be right in a way,  as these code blocks are independent from each other. In this code block we also used  `a.property = 'Node A'` but we didn't define a such node in the former code, the user has to do this by himself. So we should take this  code blocks as general block for making an edge

Yes, you are exactly right @imranzaheer612 . 
The word **lable** is used just as the name of relationship/edge, which is a bad practice and confusing. 
And these blocks of code are different from each other and not pointing to the same schema.

**Comment by GhostVaibhav** [comment]
Ok, so I will fix this typo in my next PR. Thanks for your support.

**Comment by GhostVaibhav** [comment]
This issue was resolved through PR #436
