### ISSUE TITLE
Write the extension to use those hooks

### ISSUE THREAD

**Issue by eyab** [apache/age#473]

**Comment by FahadZaheerfzr** [comment]
Fahad Zaheer

**Comment by fatimafatimaprogrammer** [comment]
hey I'm Urooj Fatima. Excited for this project

**Comment by umer200** [comment]
Hello, Its Syed Umer Tariq !!

**Comment by Steves452** [comment]
Hi, I am the new Operations Manager Steve from Vancouver Team.

**Comment by rafsun42** [comment]
Hi! It's Rafsun.

**Comment by abdulmanann** [comment]
Hi! I'm Abdul Manan. I'm excited to work on this project!

**Comment by abduu11aahh** [comment]
Hi! I am Abdullah. Excited for this project !!

**Comment by waleedahmed0001** [comment]
Hi! I am Waleed, excited to work on this project

**Comment by TalhaMunir-JD** [comment]
Hi I am Talha and I am excited to start working on this project

**Comment by JawadAliAbbasi** [comment]
Hi,
Jawad Ali here
Excited

**Comment by TalhaMunir-JD** [comment]
1.	First identify the hooks offered by the application. The hooks can be methods or functions.
2.	Write your own code that will be executed in these functions or methods. The code should be designed to modify the behavior of the application. 
3.	Register your extension with the application so that it is notified when we call those methods.
4.	Provide documentation or examples of how your extension can be used to modify the behavior of the application.

**Comment by abduu11aahh** [comment]
Here is a general overview of how an extension that uses hooks might work:

-Identify the point in the system where the extension needs to modify behavior. This could be an input or output point, an action, or a decision.
-Determine if a hook is available at that point. If so, review the documentation to understand how to use the hook and what input/output parameters are required.
-Write the extension code to use the hook. This could involve writing a new function or modifying an existing one to incorporate the hook.
-Test the extension to ensure that it works as expected. This could involve testing with various input/output scenarios or testing the extension with the system in different configurations.
-Provide documentation for the extension so that other developers know how to use it.
-Share the extension with others who may benefit from it. This could involve publishing it to a repository or marketplace or sharing it directly with other developers.

**Comment by abdulmanann** [comment]
We will begin by identifying the available hooks in the MariaDB application, which can be in the form of functions or methods. Next, we will write our own code that will be executed within these hooks to modify the behavior of the application as desired. After writing the code, we will need to register our extension with the application to ensure that it is notified when the relevant methods or functions are called.

**Comment by umer200** [comment]
In order to get started with the extension for using the hooks we need to look for points where there is need of hooks and after identifying those points we will create hooks which will be user-defined functions to perform required actions at those points. Lastly, we need to verify the results of our hooks whether it's producing the desired results after which we need to integrate those hooks in our extension after which there will be a need for documentation of all the functionalities in the extension and ultimately the extension will be made public by publishing it to some repository and share with extension marketplace.

**Comment by waleedahmed0001** [comment]
To write an extension to use hooks in MariaDB, you will need to have a good understanding of the MariaDB architecture and how the various hooks work.

So, I am sharing a link with you from which you can learn MariaDB architecture.
[Architecture Readme](https://mariadb.com/kb/en/understanding-mariadb-architecture/)
