### ISSUE TITLE
Create Deb Package for Ubuntu and Debian

### ISSUE THREAD

**Issue by eyab** [apache/age#514]

**Comment by uhayat** [comment]
Creating deb package for Ubuntu and Debian Linux distribution would make it easier for user to install AGE without compiling them on system and with few commands like bellow.
`dpkg -i postgresql-14-age`
or 
`apt install postgresql-14-age`

**Comment by sarthak-19** [comment]
Looking forward to collaborate with everyone on this project.
Indeed packaging AGE will be quiet handy for user to install extensions

**Comment by AhmarZaidi** [comment]
I'd like to work on this project. Really excited.

**Comment by Steves452** [comment]
Steve here for back up my interns. Good luck guys.

**Comment by sarthak-19** [comment]
Hi, so I found two postgreSql extensions  
1. postgresql-q3c (https://salsa.debian.org/postgresql/postgresql-q3c)
2. Postgis (https://postgis.net/)

I looked into the debian folder and tried to replicate it for the age, I created the control file, rule, copyright. 
The deb build was successful and was installing without errors, but it was not actually installing age.
The debian build was made with errors, upon inspection I found the issue was with rule file, and age is not building with make while packaging. 

I'm facing difficulty in understanding how to define the rule file. 
Is there any good resource to read and study about it. 
I tried going through official  [documentation](https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html#rules)  but didn't get much lead.

**Comment by sarthak-19** [comment]
I'm trying to understand the difference between control and control.in file and the working of rule file while packaging.
I've elaborated the issue here:
1. [Control]( https://stackoverflow.com/questions/75286431/what-is-the-difference-between-control-and-control-in-files-in-debian-packaging)
2. [Rule](https://stackoverflow.com/questions/75245064/how-to-define-rule-file-in-debian-packaging-of-a-project-which-have-a-make-file) 

Please take a look, so we can proceed further.

**Comment by uhayat** [comment]
@eyab please close this ticket as project was completed.
