### ISSUE TITLE
Create Windows Installer

### ISSUE THREAD

**Issue by eyab** [apache/age#516]

**Comment by uhayat** [comment]
Windows Installer would provide off the shelf ready to install AGE extension on all the supported PG Windows installations.

**Comment by sarthak-19** [comment]
Really excited to learn how can we make a standalone setup file for windows environment.

**Comment by AhmarZaidi** [comment]
I'd like to work on this project. Really excited.

**Comment by Steves452** [comment]
Steve here for back up my interns. Good luck guys.

**Comment by G012481632** [comment]
Any progress on this topic ? Looking forward for native Windows package !

**Comment by asltjoey** [comment]
I would like to upvote this issue to have a native Windows installer, rather than WSL, which is related to my grateful previous closed issue [https://github.com/apache/age/issues/94](url) In my case, the main reason is that the entire company's database used for analytics purpose is stored on PG13 in Windows Server. Looking forward to it.

**Comment by rsmirnov90** [comment]
If someone wanted to work on this, how would they go about structuring the project?

Let's say they wanted to use something like Wix to create an MSI installer.

Where would that go?

I am assuming it wouldn't be a part of the core repo, since none of the code would be related. Would it be a separate git repository? How would the links for the completed MSI installer make it into the "release" posts in this repo?

**Comment by sarthak-19** [comment]
The packaging related project is already completed and Debian and Cent-OS install builder script is already availabe in the [Packaging Branch](https://github.com/apache/age/tree/AGE_packaging).

For Windows installer, there are two different scripts : 
1. Inno Installer
2. Bitrock Installer

For Inno installer, PR is already merged and you can use that script to create the installer.
For Bitrock installer PR have been made and waiting to be merged [PR 1](https://github.com/apache/age/pull/963) , [PR 2](https://github.com/apache/age/pull/963)

One issue that's yet to be addressed is to compile Apache-AGE to create a Dynamic Linking Library (age.dll) for windows, which required some core modification in the code base, and then using Visual Studio to compile and generate the dll file.

**Comment by ShanGor** [comment]
There is a binary ship with PG17, if you want to compile it by yourself, you can ref to it too.
https://github.com/ShanGor/apache-age-windows

Release files: https://github.com/ShanGor/apache-age-windows/releases/tag/PG17%2Fv1.5.0-rc0
