### ISSUE TITLE
Create RPM for Rocky Linux and Scientific Linux for Open source Linux version for RHEL-8

### ISSUE THREAD

**Issue by eyab** [apache/age#520]

**Comment by uhayat** [comment]
AGE RPMS should be available on Scientific Linux, or SUSE.

**Comment by sarthak-19** [comment]
Looking forward to collaborate with everyone on this project.
Scientific Linux is a recompiled version of Red Hat Enterprise, so packaging would be different from RHEL or somewhat same?

**Comment by AhmarZaidi** [comment]
I'd like to work on this project. Really excited.

**Comment by Steves452** [comment]
Steve here for my interns. Good luck guys.

**Comment by CC-Hsu** [comment]
Hi, All,

I find that there are several SRPMs in PGDG repository for PGSQL11.
https://download.postgresql.org/pub/repos/yum/srpms/11/redhat/rhel-7-x86_64/apache-age_11-0.3.0-1.rhel7.src.rpm
https://download.postgresql.org/pub/repos/yum/srpms/11/redhat/rhel-7-x86_64/apache-age_11-0.4.0-1.rhel7.src.rpm
https://download.postgresql.org/pub/repos/yum/srpms/11/redhat/rhel-8-x86_64/apache-age_11-0.3.0-1.rhel8.src.rpm
https://download.postgresql.org/pub/repos/yum/srpms/11/redhat/rhel-8-x86_64/apache-age_11-0.4.0-1.rhel8.src.rpm

But It seems that the corresponding RPM spec file dos not appear in the Github here.

It may be great to include and update a RPM spec file based on these previous files, so that it may be keep up-to-date with the latest version of Apache AGE.

Best Regard.

**Comment by uhayat** [comment]
@eyab please close this ticket as project was completed.
