### ISSUE TITLE
DBMS does not use indexes within where clause

### ISSUE THREAD

**Issue by ed0sh** [apache/age#562]
**Describe the bug**
Age DBMS uses (gin) indexes only when the condition is specified within the match clause and not in the where clause.
Moreover, the same issue seems to be present also when trying to use a btree index on a node graphid.

**How are you accessing AGE (Command line, driver, etc.)?**
From SQL script, DBeaver CE v22.3.2.202301060755

**What data setup do we need to do?**
```pgsql
SET search_path = ag_catalog, "$user", public;

select * from create_graph('graph') ;

CREATE OR REPLACE FUNCTION public.create_random_nodes() RETURNS setof agtype AS $$
	SELECT agtype_build_map(
		'Id',
		substr(md5(random()::text), 1, 1000),
		'Value',
		(random() * 70 + 10)::integer,
		'Date',
		DATE '2018-01-01' + (random() * 700)::integer
	)
	FROM generate_series(1, 1000000);
$$ LANGUAGE sql;

select * from cypher('graph', $$
	unwind [public.create_random_nodes()] as node
	create (v:Visit {Id: node.Id, Value: node.Value, Date: node.Date})
$$) as (a agtype);

create index if not exists graph_visit_properties_index on graph."Visit" using gin (properties);
create index if not exists graph_visit_id_index on graph."Visit" using btree (id);
```

**What is the command that caused the error?**
1.  
```pgsql
select * from cypher('graph', $$
	explain analyze
	MATCH (v:Visit)
	where v.Id = "2f10d37f58b51ffd47777bd988194be7"
	RETURN v
$$) as (a agtype);
```
```
Gather  (cost=1000.00..27085.75 rows=5000 width=32) (actual time=0.289..4360.647 rows=1 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Parallel Seq Scan on "Visit" v  (cost=0.00..25585.75 rows=2083 width=32) (actual time=2849.575..4299.827 rows=0 loops=3)
        Filter: (agtype_access_operator(VARIADIC ARRAY[_agtype_build_vertex(id, _label_name('97847'::oid, id), properties), '"Id"'::agtype]) = '"2f10d37f58b51ffd47777bd988194be7"'::agtype)
        Rows Removed by Filter: 333333
Planning Time: 0.101 ms
Execution Time: 4360.860 ms
```

2.  
```pgsql
select * from cypher('graph', $$
	explain analyze
	MATCH (v:Visit)
	where id(v) = 9570149208162305
	RETURN v
$$) as (a agtype);
```
```
Gather  (cost=1000.00..27085.75 rows=5000 width=32) (actual time=0.373..2663.148 rows=1 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Parallel Seq Scan on "Visit" v  (cost=0.00..25585.75 rows=2083 width=32) (actual time=1738.598..2625.160 rows=0 loops=3)
        Filter: (age_id(_agtype_build_vertex(id, _label_name('97847'::oid, id), properties)) = '9570149208162305'::agtype)
        Rows Removed by Filter: 333333
Planning Time: 0.159 ms
Execution Time: 2663.197 ms
```

**Expected behavior**
I expect the behaviour of the DBMS to be the same as the following query:
```pgsql
select * from cypher('graph', $$
	explain analyze
	MATCH (v:Visit {Id: "2f10d37f58b51ffd47777bd988194be7"})
	RETURN v
$$) as (a agtype);
```
```
Bitmap Heap Scan on "Visit" v  (cost=43.75..3259.40 rows=1000 width=32) (actual time=0.060..0.061 rows=1 loops=1)
  Recheck Cond: (properties @> agtype_build_map('Id'::text, '"2f10d37f58b51ffd47777bd988194be7"'::agtype))
  Heap Blocks: exact=1
  ->  Bitmap Index Scan on graph_visit_properties_index  (cost=0.00..43.50 rows=1000 width=0) (actual time=0.047..0.047 rows=1 loops=1)
        Index Cond: (properties @> agtype_build_map('Id'::text, '"2f10d37f58b51ffd47777bd988194be7"'::agtype))
Planning Time: 24.067 ms
Execution Time: 0.087 ms
``` 

**Environment:**
- Docker image: apache/age:v1.1.0

**Comment by endriux** [comment]
@jrgemignani  Any news about this bug? Thank you and kind regards, Endriux

**Comment by aked21** [comment]
Hello @JoshInnis, please help @ed0sh on this. 
I suppose It is related to the discussions we had recently.

**Comment by endriux** [comment]
Dear All, any news about this issue?
Let us know if we could help or support in any ways in order to solve this bug.
Thank you for your time and consideration.

**Comment by endriux** [comment]
Kind remind. This issue is freezing one of our projects.  Let us know if we could help or support in any ways in order to solve this bug. Contact us privately and we are going to find an arrangement.
Thank you for your time and consideration.

**Comment by eyab** [comment]
@endriux @ed0sh,  please let us know how can we contact you.

**Comment by endriux** [comment]
@eyab you can reach us here or there:
[https://www.rewixecommerce.com/en/contact-us](https://www.rewixecommerce.com/en/contact-us)

**Comment by vladiksun** [comment]
As I understand this issue might me already partly fixed in https://github.com/apache/age/issues/1000.
But as described in the https://github.com/apache/age/issues/1000 we extracted a functional call from a query plan and created a functional index. As I understand GIN indexes are structural indexes hence they kick out in the MATCH clause only.

**Comment by jrgemignani** [comment]
@endriux @vladiksun We are adding more index support and working on existing index issues. They are, however, complex and difficult to debug. So, this will take some time.

**Comment by jrgemignani** [comment]
@endriux @vladiksun I've looked into this and found a few things worth pointing out. I will mention that I am no expert on indexes. What follows is from my understanding of the code underneath and how these commands are processed. And yes, as I learn and debug more of it, that can change. 

It is also worth pointing out that Cypher is its own language and some things are not directly translatable to SQL and vice versa. Just because something is possible or done a particular way in SQL doesn't necessarily translate to it being possible or done that way in Cypher. Just stating the obvious, just in case.

In the following MATCH command the two pattern matches are not the same. One is part of the MATCH clause, the other is part of the WHERE clause. The MATCH selects stuff based on its criteria and then passes it to the WHERE which then filters out stuff based on its criteria.

`MATCH (u: {key: value}) WHERE u.key = value RETURN u` 

When the indexes are applied, they are tested against the clauses, one at a time, from my understanding. When matching an index to a specific clause, the components need to match. If you look at the MATCH above, while the pattern matches are similar, they are not the same. One is done in the MATCH, the other in the WHERE. MATCH works on a path, WHERE works on an expression. An index for one won't work for the other.

Comparing the two MATCH commands that you listed, shown below, they also are not the same. One WHERE is for the id function on v, the other is for the access operator function on v. You can see this in the EXPLAIN outputs later on.

```
MATCH (v:Visit) where id(v) = 9570149208162305 RETURN v
MATCH (v:Visit) where v.Id = "2f10d37f58b51ffd47777bd988194be7" RETURN v
```

What this means is that you would need to create an index for each of these WHERE clauses, which is now possible to do.

```
psql-15.4-5432-pgsql=# CREATE INDEX btree_check_id_func ON graph."Visit" USING BTREE (age_id(_agtype_build_vertex(id, _label_name('16955'::oid, id), properties)));
CREATE INDEX
psql-15.4-5432-pgsql=#
psql-15.4-5432-pgsql=# CREATE INDEX btree_check_id ON graph."Visit" USING BTREE (agtype_access_operator(VARIADIC ARRAY[_agtype_build_vertex(id, _label_name('16955'::oid, id), properties), '"Id"'::agtype]));
CREATE INDEX
psql-15.4-5432-pgsql=# 
```
Now both of your queries will run using those indexes.
```
psql-15.4-5432-pgsql=# select * from cypher('graph', $$ explain analyze MATCH (v:Visit) where id(v) = 9570149208162305 RETURN v $$) as (a agtype);
                                                           QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on "Visit" v  (cost=139.18..11138.88 rows=5000 width=32) (actual time=0.078..0.080 rows=0 loops=1)
   Recheck Cond: (age_id(_agtype_build_vertex(id, _label_name('16955'::oid, id), properties)) = '9570149208162305'::agtype)
   ->  Bitmap Index Scan on btree_check_id_func  (cost=0.00..137.93 rows=5000 width=0) (actual time=0.073..0.074 rows=0 loops=1)
         Index Cond: (age_id(_agtype_build_vertex(id, _label_name('16955'::oid, id), properties)) = '9570149208162305'::agtype)
 Planning Time: 0.575 ms
 Execution Time: 0.196 ms
(6 rows)

psql-15.4-5432-pgsql=# select * from cypher('graph', $$ explain analyze MATCH (v:Visit) where v.Id = "2f10d37f58b51ffd47777bd988194be7" RETURN v $$) as (a agtype);
                                                                                            QUERY PLAN

------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------
 Bitmap Heap Scan on "Visit" v  (cost=207.18..11206.88 rows=5000 width=32) (actual time=0.129..0.131 rows=0 loops=1)
   Recheck Cond: (agtype_access_operator(VARIADIC ARRAY[_agtype_build_vertex(id, _label_name('16955'::oid, id), properties), '"Id"':
:agtype]) = '"2f10d37f58b51ffd47777bd988194be7"'::agtype)
   ->  Bitmap Index Scan on btree_check_id  (cost=0.00..205.93 rows=5000 width=0) (actual time=0.123..0.124 rows=0 loops=1)
         Index Cond: (agtype_access_operator(VARIADIC ARRAY[_agtype_build_vertex(id, _label_name('16955'::oid, id), properties), '"I
d"'::agtype]) = '"2f10d37f58b51ffd47777bd988194be7"'::agtype)
 Planning Time: 0.527 ms
 Execution Time: 0.256 ms
(6 rows)

psql-15.4-5432-pgsql=#
```

Hopefully, this is helps to clarify the indexes a bit. Again, this is based on debugging the index matching code.

**Comment by eyab** [comment]
@ed0sh Do you mind sending me a message at eya@apache.org to discuss this further?

**Comment by vladiksun** [comment]
@jrgemignani I'd like to give you more real life use case involving the graph traversal.
```
SET search_path = ag_catalog, "$user", public;
--- create test graph ---
DO
$do$
    BEGIN
        --LOAD 'age';
        SET search_path = ag_catalog, "$user", public;

        BEGIN
            PERFORM ag_catalog.drop_graph('test_graph', true);
        EXCEPTION WHEN OTHERS
            THEN -- ignore --
        END;

        PERFORM ag_catalog.create_graph('test_graph');
    END
$do$;

--- create test label ---
select ag_catalog.create_vlabel('test_graph','domain');
--- create test label GIN index ---
CREATE INDEX domain_gin_idx ON test_graph.domain USING GIN (properties);

--- create test label BTREE functional index on 'type' property ---
DO
$do$
    DECLARE
        collection          varchar(32);
        collections TEXT[]:= '{ domain }';
        graph_oid oid;
        index_query text:= '
            CREATE INDEX %s_btree_type_func_idx ON test_graph."%s" USING BTREE (
                ag_catalog.agtype_access_operator(VARIADIC ARRAY[ag_catalog._agtype_build_vertex(id, ag_catalog._label_name(''%s'', id), properties), ''"type"''::ag_catalog.agtype])
            );
           ';
    BEGIN
        select graphid from ag_catalog.ag_graph where name = 'test_graph' into graph_oid;
        foreach collection in array collections
            loop
                EXECUTE format(index_query, collection, collection, graph_oid);
            end loop;
    END
$do$;

--- create test relation ---
select ag_catalog.create_elabel('test_graph','parent');
--- create test relation GIN index---
CREATE INDEX parent_gin_idx ON test_graph.parent USING GIN (properties);

--- generate test data not hidden ---
DO
$do$
    BEGIN
        FOR i IN 1..10000 LOOP
                EXECUTE format('
                select * from ag_catalog.cypher(''test_graph'',
                $$
                    CREATE (Org_level_1_%s: domain {`id`:"Org_level_1_%s", `type`:"Organization", name: "Org_level_1_%s" ,`hidden`:false })
                    CREATE (Org_level_2_%s: domain {`id`:"Org_level_2_%s", `type`:"Organization", name: "Org_level_2_%s" ,`hidden`:false })
                    CREATE (Org_level_3_%s: domain {`id`:"Org_level_3_%s", `type`:"Organization", name: "Org_level_3_%s" ,`hidden`:false })
                    CREATE (Org_level_4_%s: domain {`id`:"Org_level_4_%s", `type`:"Organization", name: "Org_level_4_%s" ,`hidden`:false })
                    CREATE (Dep_level_5_%s: domain {`id`:"Dep_level_5_%s", `type`:"Department", name: "Dep_level_5_%s" ,`hidden`:false })

                    CREATE (Dep_level_5_%s)-[_rel1:`parent` { from: ''Dep_level_5_%s'', to: ''Org_level_4_%s'', hidden: false, toCollection: ''domain'', fromCollection: ''domain'' }]->(Org_level_4_%s)
                    CREATE (Org_level_4_%s)-[_rel2:`parent` { from: ''Org_level_4_%s'', to: ''Org_level_3_%s'', hidden: false, toCollection: ''domain'', fromCollection: ''domain'' }]->(Org_level_3_%s)
                    CREATE (Org_level_3_%s)-[_rel3:`parent` { from: ''Org_level_3_%s'', to: ''Org_level_2_%s'', hidden: false, toCollection: ''domain'', fromCollection: ''domain'' }]->(Org_level_2_%s)
                    CREATE (Org_level_2_%s)-[_rel4:`parent` { from: ''Org_level_2_%s'', to: ''Org_level_1_%s'', hidden: false, toCollection: ''domain'', fromCollection: ''domain'' }]->(Org_level_1_%s)
                $$
            ) as (any_vertex ag_catalog.agtype)
            ', VARIADIC ARRAY(SELECT array_fill('iter_' || i::text, '{100}')) );
            END LOOP;
    END
$do$;

--- take the plan ---
select properties from ag_catalog.cypher('test_graph',
                                         $$
EXPLAIN ANALYZE
MATCH (to:`domain` {hidden: false, id: 'Org_level_1_iter_1'})<-[any_edge:`parent`*1..10 {hidden: false, fromCollection: 'domain', toCollection: 'domain'}]-(from:`domain` {hidden: false})

WHERE
    from.type = 'Organization'
    OR from.type = 'Department'

RETURN DISTINCT properties(from)
LIMIT 1000
$$
) as (properties agtype);
```

The plan I see looks like this
![image](https://github.com/apache/age/assets/5010724/52182782-3911-4b76-81bf-755d62b3b2ba)

As I understand the **BitmapAnd** is split into **BitmapOr** that uses functional BTREE index and **Bitmap** that uses GIN index.

Probably the assumption that WHERE operates on results of a MATCH could be wrong in some scenarios ?

**Comment by jrgemignani** [comment]
@vladiksun It is a bit complicated how these components integrate together and how PostgreSQL may decide how to deal with them. Yes, the WHERE clause can also be part of other clauses, but my examples here are referring to MATCH specifically.

As mentioned above, the WHERE clause works on some **expression** passed to it from somewhere. The MATCH clause works on a **path** and the **property constraints** provided in the path. These two are different and an index for one likely won't work for the other. All of the examples I have seen so far suggest that they won't. (1)

The WHERE clause is added to the **jointree** as a **FromExpr** **AND**ed with the clause that it is part of, MATCH in these cases. MATCH's **property constraints** are also added to the **jointree** as a **FromExpr**. 

We provide this new query tree back to PostgreSQL where the planner/optimizer is basically free to do what ever it likes. So, it is not surprising to see them mixed together since they are **AND**ed together. It is attempting to optimize the query.

Hopefully this helps

(1) When the indexes are matched to their clauses, the match routines looks to match their components. A **contains** won't match to an **access** operator because they are two different functions with different arguments.
