### ISSUE TITLE
Index advice for hop queries

### ISSUE THREAD

**Issue by xephtar** [apache/age#690]
We have 6 types of nodes. There is an one relation between them like below

```
typeOne -[REL]-> typeTwo
typeOne -[REL]-> typeThree
typeOne -[REL]-> typeFour
typeOne -[REL]-> typeFive
typeOne -[REL]-> typeSix
```

We have queries. They search all typeOne nodes like below
```

MATCH (:typeTwo{value:"searchingValue}) - [:REL*..100]- (node:typeOne) RETURN node.prop;
MATCH (:typeThree{value:"searchingValue2}) - [:REL*..100]- (node:typeOne) RETURN node.prop;
MATCH (:typeFour{value:"searchingValue3}) - [:REL*..100]- (node:typeOne) RETURN node.prop;
MATCH (:typeFive{value:"searchingValue4}) - [:REL*..100]- (node:typeOne) RETURN node.prop;
MATCH (:typeSix{value:"searchingValue5}) - [:REL*..100]- (node:typeOne) RETURN node.prop;
```

It takes too much time to search. We can't search with direction because we want to get each typeOne node who has relations.

How index should we add to make it faster?

We can't change the graph because we can achieve same need with neo4j already.
We want to move it AGE. Can you help us? How does index work for AGE?

**Comment by rafsun42** [comment]
@xephtar Have you checked out this issue #628 yet? It looks like the problem being discusses is similar to yours.

**Comment by xephtar** [comment]
I checked but the given solution is not eligible for us. Giving the direction of relation breaks our hop logic

**Comment by jrgemignani** [comment]
@xephtar How much is too much time? Too much is rather subjective. Could you put in an EXPLAIN ANALYZE to dump what it is doing?

In general, using a directionless match with variable length edges is an intensive search. Recall that directionless means any edge on a node is a valid path.

**Comment by jrgemignani** [comment]
Btw, the VLE component itself doesn't use indexes but, the surrounding logic might. I would need a dataset to look at to get a better idea.

**Comment by humzakt** [comment]
Indexing in Apache AGE can help improve the performance of your queries, similar to how indexing works in Neo4j. Since Apache AGE is built on top of PostgreSQL, you can leverage PostgreSQL's native indexing capabilities to create indices on the properties of your vertices.

To speed up your queries, you can create indices on the value property for each of the node types (typeTwo to typeSix). Here's how you can create indices for each node type:

```
CREATE INDEX type_two_value_idx ON ag_vertex(typeTwo) USING btree (properties->>'value');
CREATE INDEX type_three_value_idx ON ag_vertex(typeThree) USING btree (properties->>'value');
CREATE INDEX type_four_value_idx ON ag_vertex(typeFour) USING btree (properties->>'value');
CREATE INDEX type_five_value_idx ON ag_vertex(typeFive) USING btree (properties->>'value');
CREATE INDEX type_six_value_idx ON ag_vertex(typeSix) USING btree (properties->>'value');
```

These indices will improve the performance of your queries when searching for nodes based on the value property.

However, it's worth noting that using a variable-length path pattern with a large maximum depth (e.g., [:REL*..100]) can still lead to slow query performance, as it requires traversing a significant portion of the graph. If possible, try to reduce the maximum depth to a smaller value based on your specific use case.

In addition, you can optimize your queries by merging them into a single query using the UNION operator, which can help reduce the overall query execution time:

```
MATCH (:typeTwo{value:"searchingValue"}) - [:REL*..100]- (node:typeOne) RETURN node.prop
UNION
MATCH (:typeThree{value:"searchingValue2"}) - [:REL*..100]- (node:typeOne) RETURN node.prop
UNION
MATCH (:typeFour{value:"searchingValue3"}) - [:REL*..100]- (node:typeOne) RETURN node.prop
UNION
MATCH (:typeFive{value:"searchingValue4"}) - [:REL*..100]- (node:typeOne) RETURN node.prop
UNION
MATCH (:typeSix{value:"searchingValue5"}) - [:REL*..100]- (node:typeOne) RETURN node.prop;

```

**Comment by xephtar** [comment]
Thanks for advices.

**Comment by xephtar** [comment]
Hi,

Years after initially optimizing this query in Neo4j, we're now considering moving back to Apache AGE. Our graph structure is as follows:

A Label - HAS_Y -> Y Label
A Label - HAS_Z -> Z Label

The traversal logic we use is:

MATCH (n:Y {property_example: 123})-[r*..4]-(d:A)
RETURN d.property_found AS property_found
LIMIT 50
UNION ALL
MATCH (n:Z {property_example: 123})-[r*..4]-(d:A)
RETURN d.property_found AS property_found
LIMIT 50

We expect around 500 million nodes and 3–4x that number in relationships.

Question:
What kind of indexing strategy would you recommend for optimizing traversal performance in Apache AGE for this type of pattern?

Any guidance or best practices regarding node properties or relationship indexing (if supported) would be highly appreciated.

Thanks in advance!
