### ISSUE TITLE
Research about PNSI and RTE

### ISSUE THREAD

**Issue by eyab** [apache/age#744]

**Comment by kenwoon** [comment]
You have provided RTE as <RelTableIndex>, but is it not <RangeTblEntry> instead? Just confused as these two serve different purposes.

**Comment by MuhammadZeeshan03** [comment]
I believe you have figured it out up till now. If not, then yes, RTE stands for `RangeTblEntry` for this project named RTE to PNSI.

**Comment by M4rcxs** [comment]
- **RTE** works identifying a table or view and specifying the name by which it is referenced in other parts of the query. However, it's important to note that in the internal representation of the query tree, the RTEs are referenced by number rather than by name. This means that even if there are duplicate names in the SQL statement, it doesn't cause any ambiguity or conflict at the query tree level. [PostgreSQL Docs](https://www.postgresql.org/docs/8.1/rules.html)

**Comment by M4rcxs** [comment]
- **PNSI** structure is essential for PostgreSQL's query processing, as it handles object referencing, conflict resolution, and overall query accuracy. These elements encompass a wide range of objects, including tables, columns, functions, and more.

[PNSI Struct](https://doxygen.postgresql.org/structParseNamespaceItem.html)
