### ISSUE TITLE
Research what needs to be done to implement List Comprehension

### ISSUE THREAD

**Issue by eyab** [apache/age#771]

**Comment by mutaharaamir** [comment]
We could start by looking at how list comprehensions are implemented in existing languages such as python, perl and scala. I think CPython is a good place to start because Python's list comprehension syntax is quite clean, and it is written in C which should give us pointers on how to implement it in AGE. 

According to [this](https://stackoverflow.com/questions/62281997/where-are-list-comprehensions-implemented-in-cpython-source-code) and [this](https://stackoverflow.com/questions/24482810/do-python-list-comprehensions-get-converted-to-pure-c) post on stackoverflow, list comprehensions are converted directly to bytecode instead of being converted to C as an intermediate step. Perhaps this could give us some indication of how to proceed?

**Comment by MuhammadTahaNaveed** [comment]
List comprehension was implemented and added by PR #1610 .
