### ISSUE TITLE
Pypi instruction for installing apache-age-python is not correct

### ISSUE THREAD

**Issue by Munmud** [apache/age#784]
Dependency mismatch at Apache Age Repo and [`pypi package`](https://pypi.org/project/apache-age-python/)
This is happening because the project decription at pypi.org is not correct.

### apache/age python driver repo dependency requirements.txt
```txt
pip install ﻿psycopg2 --no-binary :all: psycopg2
pip install antlr4-python3-runtime==4.11.1
pip install setuptools
```

### pypi.org dependency requirements.txt
```txt
sudo apt-get install python3-dev libpq-dev
pip install --no-binary :all: psycopg2
pip install antlr4-python3-runtime
```

By followig pypi.org project description instruction user getting this error
```
  File "/home/moontasir/Desktop/pyage/myenv/lib/python3.10/site-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).
```

**Comment by hammadsaleemm** [comment]
To resolve the issue, I would recommend following the instructions from the Apache Age repository's requirements.txt file instead of the PyPI project description instructions. This should ensure that you are using the correct versions of the dependencies that are compatible with Apache Age.

You can install the recommended dependencies by running the following commands:
`pip install psycopg2 --no-binary :all: psycopg2
pip install antlr4-python3-runtime==4.11.1
pip install setuptools
`

If you continue to experience issues, it may be helpful to check the versions of the installed dependencies using pip freeze, and compare them to the requirements specified in the requirements.txt file.
